Fixed a lot of merge conflicts from Genki-S

diff --git a/zshfiles/zshrc b/zshfiles/zshrc
--- a/zshfiles/zshrc
+++ b/zshfiles/zshrc
@@ -10,14 +10,27 @@ compinit
 # Jump into tmux session automatically {{{
 export AUTO_TMUX_SESSION_NAME="j605"
 if [ -z $TMUX ]; then
+	# assume $SHELL is zsh, and open org mode automatically
+	# (and set window name 'org' so that it can be used by select-window)
 	tmux attach-session -t "$AUTO_TMUX_SESSION_NAME"
 	if [ $? -ne 0 ]; then
-		tmux new-session -s "$AUTO_TMUX_SESSION_NAME"
+		# Init new tmux session (play around with some tmux scripting)
+		tmux new-session -s "$AUTO_TMUX_SESSION_NAME" -n "org" "$SHELL -i -c 'org'"
 	fi
 	# exit
 	# Not exit in order to use shell outside of tmux on occasion...
 fi
 # }}}
+
+# FIXME: this should be done using LaunchAgent, but it does not work for now
+tmux list-session | grep 'wordstack' > /dev/null
+if [ $? -ne 0 ]; then
+  TMUX='' tmux new-session -d -s 'wordstack' -n 'wordstack' '/usr/local/bin/node ~/dotfiles/miscfiles/word-stack-server.js'
+fi
+tmux list-session | grep 'devdocs' > /dev/null
+if [ $? -ne 0 ]; then
+  TMUX='' tmux new-session -d -c "$HOME/vendor/devdocs" -s 'devdocs' -n 'devdocs' '/usr/local/opt/rbenv/shims/rackup'
+fi
 
 # ==================================================
 # fpath {{{
@@ -40,7 +53,7 @@ ZSH_THEME=""
 COMPLETION_WAITING_DOTS="true"
 
 # plugins to load from oh-my-zsh/plugins
-plugins=(git git-flow tmux command-not-found)
+plugins=(git git-flow tmux command-not-found rbenv)
 
 source $ZSH/oh-my-zsh.sh
 
@@ -164,27 +177,6 @@ DISABLE_AUTO_TITLE=true
 # Welcome Message {{{
 # ==================================================
 # uname -a
-# cat <<HEREDOC
-  # _____                                   __  ___   ___ _   __  
- # |  __ \                                 /_ |/ _ \ / _ (_) / /  
- # | |  | | ___    _   _  ___  _   _ _ __   | | | | | | | | / /   
- # | |  | |/ _ \  | | | |/ _ \| | | | '__|  | | | | | | | |/ /    
- # | |__| | (_) | | |_| | (_) | |_| | |     | | |_| | |_| / / _ _ 
- # |_____/ \___/   \__, |\___/ \__,_|_|     |_|\___/ \___/_/ (_|_)
-                  # __/ |                                         
-                 # |___/                                          
-# HEREDOC
-
-# # Random reminders
-# echo
-# echo "=== Random Reminder ==="
-# shuf -n 1 ~/random_reminders.txt
-
-# # Oblique Strategies
-# echo
-# echo "=== Oblique Strategy ==="
-# shuf -n 1 ~/oblique_strategies.txt
-
 # # Tmuxinator project list
 # if [ -z "$TMUX" ]; then
 	# echo
@@ -212,5 +204,13 @@ if ! grep $start_token $hosts_file &> /dev/null; then
 fi
 # }}}
 # ==================================================
+
+# clean $path
+# http://blog.n-z.jp/blog/2013-12-12-zsh-cleanup-path.html
+path=(
+	# allow directories only (-/)
+	# reject world-writable directories (^W)
+	${^path}(N-/^W)
+)
 
 # vim: foldmethod=marker
